# Generated by Django 3.1.3 on 2022-06-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='date',
            field=models.CharField(max_length=250, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='meals',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merchants',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merchants',
            name='rating',
            field=models.CharField(max_length=250, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='merchants',
            name='reviews',
            field=models.CharField(max_length=250, null=True, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='meals_time',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
    ]
