# Generated by Django 3.1.3 on 2022-06-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0002_auto_20220611_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='start_date',
            field=models.CharField(max_length=150, null=True, verbose_name='Start Date'),
        ),
    ]
