# Generated by Django 3.1.3 on 2022-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0003_basket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='start_date',
            field=models.CharField(max_length=150, null=True, verbose_name='Start Date'),
        ),
    ]
